---
title: "COVID-19 in South Carolina"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
    vertical_layout: fill
    theme: flatly
    css: sc_dash.css
    source_code: "https://github.com/jacob-long/SC-COVID-19-Dashboard"
    navbar:
      - {title: "Jacob Long", href: "https://jacob-long.com", icon: "fa-user-edit"}
    
---

```{r setup, include=FALSE}
library(flexdashboard)
```

```{r}
library(tidyverse)
library(magrittr)
library(jtools)
library(extrafont)
library(ggplot2)
library(lubridate)
library(plotly)
library(tidycensus)
library(tsibble)
library(slider)

extrafont::font_import("./IBM-Plex-Sans", prompt = FALSE)

# Grab testing data from healthdata.gov
tests <- read_csv("https://healthdata.gov/api/views/j8mb-icvb/rows.csv?accessType=DOWNLOAD") %>%
  filter(state == "SC")
# They are separated into one row each for positive and negative test results :|
neg_tests <- filter(tests, overall_outcome == "Negative") %>%
  transmute(
    new_negatives = new_results_reported,
    date = date
  )
pos_tests <- filter(tests, overall_outcome == "Positive") %>%
  transmute(
    new_positives = new_results_reported,
    date = date
  )

tests <- inner_join(neg_tests, pos_tests, by = "date") %>%
  transmute(
    date = date,
    new_positives = new_positives,
    new_tests = new_positives + new_negatives,
    pos_rate = new_positives/new_tests
  )

# Grab hospitalization data from healthdata.gov
hosp <- read_csv("https://healthdata.gov/api/views/g62h-syeh/rows.csv?accessType=DOWNLOAD") %>% 
  filter(state == "SC") %>%
  arrange(date) %>%
  mutate(
    hospitalized = total_adult_patients_hospitalized_confirmed_and_suspected_covid + total_pediatric_patients_hospitalized_confirmed_and_suspected_covid
  ) %>%
  select(
    date, hospitalized
  ) %>%
  mutate(
    hospitalized = ifelse(is.na(hospitalized), yes = 0, no = hospitalized)
  )

# Grab hospitalization data from COVID tracking project (now defunct)
hosp_old <- read_csv("https://api.covidtracking.com/v1/states/daily.csv") %>%
  mutate(
    date = lubridate::as_date(as.character(date))
  ) %>%
  filter(state == "SC") %>%
  arrange(date) %>%
  filter(date != lag(date)) %>%
  select(
    date = date,
    hospital = hospitalizedCurrently,
  )

# Replacing missing government data with COVID tracking project data
hosp$hospitalized[hosp$date < as_date("2020-07-26")] <-
  c(rep(NA,3), hosp_old$hospital[hosp_old$date < as_date("2020-07-26")])

# Grab cases from NYTimes
cases <- 
  read_csv("https://github.com/nytimes/covid-19-data/raw/master/us-states.csv") %>%
  filter(state == "South Carolina") %>%
  mutate(
    new_cases = cases - lag(cases),
    new_deaths = deaths - lag(deaths)
  )

sc <- full_join(cases, tests, by = "date") %>%
  full_join(hosp, by = "date") %>%
  arrange(date)

sc %<>%
  mutate(
    new_positives_roll = slide_dbl(new_positives, ~mean(.x), .before = 6),
    new_cases_roll = slide_dbl(new_cases, ~mean(.x), .before = 6),
    # New column to remove points when daily reporting ends
    new_cases_points = ifelse(date < as_date("2021-06-01"), yes = new_cases, no = NA),
    new_tests_roll = slide_dbl(new_tests, ~mean(.x), .before = 6),
    total_tests = cumsum(replace_na(new_tests, 0)),
    pos_rate_roll = slide_dbl(pos_rate, ~mean(.x, na.rm = T), .before = 6),
    new_deaths_points = ifelse(date < as_date("2021-06-01"), yes = new_deaths, no = NA),
    new_deaths_roll = slide_dbl(new_deaths, ~mean(.x, na.rm = T), .before = 6),
    hosp_roll = slide_dbl(hospitalized, ~mean(.x), .before = 6),
    day_of_week = factor(wday(date)),
    day_of_week = relevel(day_of_week, ref = "7")
  ) %>%
  filter(!(date == today("America/New_York") & new_positives == 0))

num_points <- as.numeric(range(sc$date)[2] - range(sc$date)[1])
```

Statewide Statistics
=======================================================================

Row {.tabset}
-----------------------------------------------------------------------

### Daily Cases

```{r}
ggplot(sc, aes(x = date, y = new_cases_points)) +
  geom_point() +
  geom_path(aes(y = new_cases_roll), color = "#73000a") +
  geom_point(inherit.aes = F, aes(x = date, y = new_cases_roll,
                                  text = paste(
    "Date:", date,
    paste0("\nCases: ", ifelse(new_cases == 0, yes = "Not reported", no = round(new_cases)), 
           "\n7-day average deaths per day: ", round(new_cases_roll))
  )), size = 0.1, color = "#73000a") +
  theme_nice(base_family = "IBM Plex Sans") +
  ylab("New cases/day") +
  xlab("Date") +
  scale_y_log10(labels = scales::label_number(accuracy = 1, big.mark = ","),
                limits = c(1, 50000)) +
  geom_vline(xintercept = as.numeric(as.Date("2020-05-04")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2020-04-07")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-01-01")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-03-08")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-06-01")),
             linetype = "dotted", color = "black") +
  geom_vline(xintercept = as.numeric(as.Date("2021-07-03")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-09-23")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2021-12-25")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2022-06-01")),
             linetype = "dashed", color = "#ff6673") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") -> cases_plot

gcases <- ggplotly(cases_plot, tooltip = c("text")) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-04-07"))),
    y = c(4),
    text = c( '"Home or Work"\norder'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-05-04"))),
    y = c(0.35),
    text = c('"Home or Work"\norder lifted'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-01-01"))),
    y = c(0.5),
    text = c('Vaccines available\nto high-risk'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-03-08"))),
    y = c(1.75),
    text = c('Vaccines widely\navailable'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-06-01"))),
    y = c(4),
    text = c('<i>Daily case\nreporting ends</i>'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("black"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-07-03"))),
    y = c(0.75),
    text = c( 'Delta variant\nbecomes dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-09-23"))),
    y = c(1.75),
    text = c('Booster rollout\nbegins'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-12-25"))),
    y = c(1),
    text = c('Omicron variant\nbecomes dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2022-06-01"))),
    y = c(1),
    text = c('Omicron BA.4/BA.5\nbecome dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  layout(legend = list(x = 0.8, y = 0.1)) 

font <- list(
  family = "IBM Plex Sans",
  size = 15,
  color = "white"
)
label <- list(
  bgcolor = "#232F34",
  bordercolor = "transparent",
  font = font
)

gcases <- gcases %>% 
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(hovermode = "x")

gcases
```

### Positive Test %

```{r}
ggplot(sc, aes(x = date, y = pos_rate)) +
  geom_point(aes(text = paste(
    "Date:", date,
    "\nPercentage positive =", paste0(round(pos_rate * 100, 1), "%")
    )
  )) + 
  geom_path(data = filter(sc, date > as_date("2020-03-15")),
            aes(y = pos_rate_roll), color = "#73000a") +
  theme_nice(base_family = "IBM Plex Sans") +
  ylab("% of tests that are positive") +
  scale_y_continuous(labels = scales::percent_format(accuracy = 1), limits = c(0, .30)) +
  xlab("Date") +
  geom_vline(xintercept = as.numeric(as.Date("2020-05-04")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2020-04-07")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-01-01")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-03-08")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-07-03")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-09-23")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2021-12-25")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2022-06-01")),
             linetype = "dashed", color = "#ff6673") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") -> pos_rate

gpos <- ggplotly(pos_rate, tooltip = c("text"))

font <- list(
  family = "IBM Plex Sans",
  size = 15,
  color = "white"
)
label <- list(
  bgcolor = "#232F34",
  bordercolor = "transparent",
  font = font
)


smooth1 <- paste0(
  "Date: ", as.Date(round(gpos$x$data[[2]]$x), origin = "1970-01-01"), "\n",
  "7-day average % positive = ", round(gpos$x$data[[2]]$y * 100, 1), "%"
)

gpos <- gpos %>% 
  add_annotations(
    x = c(as.numeric(as.Date("2020-03-28"))),
    y = c(0.02),
    text = c( '"Home or Work"\norder'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-05-04"))),
    y = c(0.27),
    text = c('"Home or Work"\norder lifted'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-12-20"))),
    y = c(0.02),
    text = c('Vaccines available\nto high-risk'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-03-08"))),
    y = c(0.25),
    text = c('Vaccines widely\navailable'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-07-03"))),
    y = c(0.3),
    text = c( 'Delta variant\nbecomes dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-09-23"))),
    y = c(0.25),
    text = c('Booster rollout\nbegins'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-12-25"))),
    y = c(0.30),
    text = c('Omicron variant\nbecomes dominant'),
    showarrow = TRUE,
    bgcolor = "#FFFFFF",
    ax = 125,
    ay = 0,
    xref = "x",
    yref = "y",
    arrowcolor = "#73000a",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2022-06-01"))),
    y = c(0.02),
    text = c('Omicron BA.4/BA.5\nbecome dominant'),
    showarrow = TRUE,
    bgcolor = "#FFFFFF",
    ax = 50,
    ay = 0,
    xref = "x",
    yref = "y",
    arrowcolor = "#73000a",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')) %>%
  style(text = smooth1, traces = 2) %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(hovermode = "x")

gpos

```

Row {.tabset}
-----------------------------------------------------------------------

### Deaths per day

```{r}
ggplot(sc, aes(x = date, y = new_deaths_points)) +
  geom_point() +
  geom_path(aes(y = new_deaths_roll), color = "#73000a") +
  geom_point(inherit.aes = F, aes(x = date, y = new_deaths_roll,
                                  text = paste(
    "Date:", date,
    paste0("\nDeaths: ", ifelse(new_deaths == 0, yes = "Not reported", no = round(new_deaths)), 
           "\n7-day average deaths per day: ", round(new_deaths_roll))
  )), size = 0.1, color = "#73000a") +
  theme_nice(base_family = "IBM Plex Sans") +
  ylab("Deaths/day") +
  ylim(0, 150) +
  xlab("Date") +
  geom_vline(xintercept = as.numeric(as.Date("2020-05-04")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2020-04-07")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-01-01")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-03-08")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-06-01")),
             linetype = "dotted", color = "black") +
  geom_vline(xintercept = as.numeric(as.Date("2021-07-03")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-09-23")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2021-12-25")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2022-06-01")),
             linetype = "dashed", color = "#ff6673") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y") -> deaths

gdeath <- ggplotly(deaths, tooltip = "text")

smooth1 <- paste0(
  "Date: ", as.Date(round(gdeath$x$data[[2]]$x), origin = "1970-01-01"), "\n",
  "7-day average # deaths = ", round(gdeath$x$data[[2]]$y, 0)
)

gdeath <- ggplotly(deaths, tooltip = "text") %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-04-07"))),
    y = c(135),
    text = c( '"Home or Work"\norder'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-05-04"))),
    y = c(100),
    text = c('"Home or Work"\norder lifted'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-01-01"))),
    y = c(125),
    text = c('Vaccines available\nto high-risk'),
    showarrow = TRUE,
    bgcolor = "#FFFFFF",
    ax = -75,
    ay = 0,
    xref = "x",
    yref = "y",
    arrowcolor = c("#466A9F"),
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-03-08"))),
    y = c(150),
    text = c('Vaccines widely\navailable'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-06-01"))),
    y = c(75),
    text = c('<i>Daily\nreporting ends</i>'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("black"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-07-03"))),
    y = c(115),
    text = c( 'Delta variant\nbecomes dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-09-23"))),
    y = c(150),
    text = c('Booster rollout\nbegins'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-12-25"))),
    y = c(100),
    text = c('Omicron variant\nbecomes dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2022-06-01"))),
    y = c(100),
    text = c('Omicron BA.4/BA.5\nbecome dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  # style(text = smooth1, traces = 2) %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(hovermode = "x")

gdeath
```

### Current Hospitalizations

```{r}
ggplot(sc, aes(x = date, y = hospitalized)) +
  geom_point() +
  geom_path(aes(y = hosp_roll), color = "#73000a") +
  geom_point(inherit.aes = F, aes(x = date, y = hosp_roll,
                                  text = paste(
    "Date:", date,
    paste0("\nHospitalized: ", no = round(hospitalized), 
           "\n7-day average number in hospital: ", round(hosp_roll))
  )), size = 0.1, color = "#73000a") +
  theme_nice(base_family = "IBM Plex Sans") +
  ylab("Currently in hospital") +
  ylim(0, 3000) +
  xlab("Date") +
  geom_vline(xintercept = as.numeric(as.Date("2020-05-04")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2020-04-07")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-01-01")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-03-08")),
             linetype = "dashed", color = "#466A9F") + 
  geom_vline(xintercept = as.numeric(as.Date("2021-07-03")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2021-09-23")),
             linetype = "dashed", color = "#466A9F") +
  geom_vline(xintercept = as.numeric(as.Date("2021-12-25")),
             linetype = "dashed", color = "#ff6673") +
  geom_vline(xintercept = as.numeric(as.Date("2022-06-01")),
             linetype = "dashed", color = "#ff6673") +
  scale_x_date(date_breaks = "3 months", date_labels = "%b %Y")  -> hosp

ghosp <- ggplotly(hosp, tooltip = "text")

smooth1 <- paste0(
  "Date: ", as.Date(round(ghosp$x$data[[2]]$x), origin = "1970-01-01"), "\n",
  "3-day average # in hospital = ", round(ghosp$x$data[[2]]$y, 0)
)

ann <- list(
  x = c(as.numeric(as.Date("2020-04-16"))),
  y = c(200),
  xref = "x",
  yref = "y",
  text = c("Not reported\nuntil May"),
  showarrow = FALSE,
  arrowhead = 6,
  arrowsize = 0.01,
  ax = -50,
  ay = 40,
  bgcolor = "white",
  font = list(
    color = "#000000",
    family = "IBM Plex Sans"
  )
)

ghosp <- ggplotly(hosp, tooltip = "text") %>%
  layout(annotations = ann) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-04-07"))),
    y = c(1000),
    text = c( '"Home or Work"\norder'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2020-05-04"))),
    y = c(2000),
    text = c('"Home or Work"\norder lifted'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-01-01"))),
    y = c(200),
    text = c('Vaccines available\nto high-risk'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-03-08"))),
    y = c(2600),
    text = c('Vaccines widely\navailable'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-07-03"))),
    y = c(3000),
    text = c( 'Delta variant\nbecomes dominant'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-09-23"))),
    y = c(200),
    text = c('Booster rollout\nbegins'),
    showarrow = FALSE,
    bgcolor = "#FFFFFF",
    # bordercolor = "#000000",
    font = list(color = c("#466A9F"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2021-12-25"))),
    y = c(3000),
    text = c('Omicron variant\nbecomes dominant'),
    showarrow = TRUE,
    bgcolor = "#FFFFFF",
    ax = 125,
    ay = 0,
    xref = "x",
    yref = "y",
    arrowcolor = c("#73000a"),
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  add_annotations(
    x = c(as.numeric(as.Date("2022-06-01"))),
    y = c(2000),
    text = c('Omicron BA.4/BA.5\nbecome dominant'),
    showarrow = TRUE,
    bgcolor = "#FFFFFF",
    ax = 0,
    ay = 0,
    xref = "x",
    yref = "y",
    arrowcolor = c("#73000a"),
    font = list(color = c("#73000a"),
                family = 'IBM Plex Sans')
  ) %>%
  # style(text = smooth1, traces = 2) %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(hovermode = "x")

ghosp
```

Maps
=======================================================================

Row {.tabset}
-----------------------------------------------------------------------

```{r include = FALSE}
options(tigris_use_cache = TRUE)

census_api_key(Sys.getenv("CENSUS_API_KEY"))

# Too many 404 errors trying to download this data with GH Actions
# acs_dat <- get_acs("county", state = "SC", 
#                    variables = c(population = "B01003_001"),
#                    year = 2018, survey = "acs5",
#                    geometry = TRUE, keep_geo_vars = FALSE) %>%
#   dplyr::select(fips = GEOID, population = estimate, geometry)
# saveRDS(acs_dat, "acs_dat.RDS")

acs_dat <- readRDS("acs_dat.RDS")

nytc <- 
  read_csv("https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-counties.csv") %>%
  filter(state == "South Carolina") %>%
  inner_join(select(as_tibble(acs_dat), -geometry), by = "fips") %>%
  as_tsibble(key = county, index = date) %>%
  group_by_key() %>%
  mutate(
    lag_cases = lag(cases),
    lag_cases = replace_na(lag_cases, 0),
    new_cases = cases - lag_cases,
    lag_deaths = lag(deaths),
    lag_deaths = replace_na(lag_deaths, 0),
    new_deaths = deaths - lag_deaths,
    new_cases_avg = slide_dbl(new_cases, ~mean(.x), .before = 6),
    new_deaths_avg = slide_dbl(new_deaths, ~mean(.x), .before = 6),
    lag_cases_avg = lag(new_cases_avg, 6),
    lag_deaths_avg = lag(new_deaths_avg, 6),
    case_growth = new_cases_avg / lag_cases_avg + 
      # Adding random noise because ggplotly has an error when two fills
      # have exactly the same value and I want to use hoveron = "fill"
      # https://github.com/ropensci/plotly/issues/1641
      rnorm(1, sd = .001),
    death_growth = new_deaths_avg / lag_deaths_avg,
  ) %>%
  filter(date == max(date)) %>%
  mutate(
    cases_per_cap = cases / population,
    new_cases_cap = (new_cases_avg / population) * 100000,
    # Adding random noise because ggplotly has an error when two fills
    # have exactly the same value and I want to use hoveron = "fill"
    # https://github.com/ropensci/plotly/issues/1641
    deaths_per_cap = deaths / population + abs(rnorm(1, sd = 0.000001)),
    # Adding random noise because ggplotly has an error when two fills
    # have exactly the same value and I want to use hoveron = "fill"
    # https://github.com/ropensci/plotly/issues/1641
    deaths = deaths + rnorm(1, sd = 0.1)
  ) %>%
  as_tibble()
```

### Recent Case Density

```{r}
inner_join(acs_dat, nytc, by = "fips") %>%
  ggplot(aes(fill = new_cases_cap,
             text = paste(
               county, "County",
               "\n", ifelse(
                 is.finite(new_cases_cap),
                 yes = paste0(round(new_cases_cap, 0), " daily cases per 100,000 people"),
                 no = "No data")
             ))) +
  geom_sf() +
  ggthemes::theme_map() +
  # ggtitle("Total cases per capita") +
  scale_fill_gradient(low = "white", high = scales::muted("red"),
                      limits = c(1, 50), oob = scales::squish) -> scmap

ann <- list(
  y = c(34.0007100, 32.784618, 34.852619, 33.689060),
  x = c(-81.0348100, -79.940918, -82.394012, -78.886696),
  xref = "x",
  yref = "y",
  text = c("Columbia", "Charleston", "Greenville", "Myrtle Beach"),
  showarrow = TRUE,
  arrowhead = 6,
  arrowsize = 0.01,
  ax = 10,
  ay = 10,
  bgcolor = "#FFFFFF",
  font = list(
    size = 10,
    color = "#000000",
    family = "IBM Plex Sans"
  )
)

pmap <- ggplotly(scmap, tooltip = "text") %>%
  style(hoveron = "fill") %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(annotations = ann) %>%
  hide_guides()

pmap
```

### Weekly Case Growth 

```{r}
inner_join(acs_dat, nytc, by = "fips") %>%
  ggplot(aes(fill = case_growth,
             text = paste(
               county, "County",
               "\nCase growth =", ifelse(
                 is.finite(case_growth),
                 yes = paste0(round((case_growth - 1) * 100), "%"),
                 no = "No data")
             ))) +
  geom_sf() +
  # geom_point(y = 34.0007100, y = -81.0348100, ) +
  ggthemes::theme_map() +
  # ggtitle("New case growth") +
  scale_fill_gradient2(low = scales::muted("blue"),
                       high = scales::muted("red"), midpoint = 1,
                       limits = c(0.5, 2), oob = scales::squish,
                       breaks = c(0.5, 1, 1.5, 2),
                       labels = c(
                         "Shrinking rapidly",
                         "Staying the same", 
                         "Going up 50% per week", 
                         "Doubling every week"
                       ),
                       name = "New cases are...",
                       guide = "legend"
                      ) -> scmap

pmap <- ggplotly(scmap, tooltip = "text") %>%
  style(hoveron = "fill") %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(annotations = ann) %>%
  hide_guides()

pmap
```

### Total Case Density 

```{r}
inner_join(acs_dat, nytc, by = "fips") %>%
  ggplot(aes(fill = cases_per_cap,
             text = paste(
               county, "County",
               "\n% population infected =", ifelse(
                 is.finite(cases_per_cap),
                 yes = paste0(round(cases_per_cap * 100, 3), "%"),
                 no = "No data")
             ))) +
  geom_sf() +
  ggthemes::theme_map() +
  # ggtitle("Total cases per capita") +
  scale_fill_gradient(low = "white", high = scales::muted("red")) -> scmap

pmap <- ggplotly(scmap, tooltip = "text") %>%
  style(hoveron = "fill") %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(annotations = ann) %>%
  hide_guides()

pmap
```

### Deaths per Capita

```{r}
inner_join(acs_dat, nytc, by = "fips") %>%
  ggplot(aes(fill = deaths_per_cap,
             text = paste(
               county, "County",
               "\n% population deceased =", ifelse(
                 is.finite(deaths_per_cap),
                 yes = paste0(round(deaths_per_cap * 100, 3), "%"),
                 no = "No data")
             ))) +
  geom_sf() +
  ggthemes::theme_map() +
  # ggtitle("Deaths per capita") +
  scale_fill_gradient(low = "white", high = scales::muted("red")) -> scmap

pmap <- ggplotly(scmap, tooltip = "text") %>%
  style(hoveron = "fill") %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(annotations = ann) %>%
  hide_guides()

pmap
```

### Total Deaths

```{r}
inner_join(acs_dat, nytc, by = "fips") %>%
  ggplot(aes(fill = deaths,
             text = paste(
               county, "County",
               "\n# of deaths =", ifelse(
                 is.finite(deaths),
                 yes = round(deaths),
                 no = "No data")
             ))) +
  geom_sf() +
  ggthemes::theme_map() +
  # ggtitle("Total deaths") +
  scale_fill_gradient(low = "white", high = scales::muted("red")) -> scmap

pmap <- ggplotly(scmap, tooltip = "text") %>%
  style(hoveron = "fill") %>%
  style(hoverlabel = label) %>%
  layout(font = font) %>%
  layout(annotations = ann) %>%
  hide_guides()

pmap
```


