on:
  push:
    paths:
      - sc_dashboard.Rmd
  schedule: 
  - cron: '0 21 * * *' 

name: Render Dashboard

jobs:
  render:
    name: Render Dashboard
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "flexdashboard", "tidyverse", "jtools", "lubridate", "extrafont", "ggplot2", "plotly"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("sc_dashboard.Rmd", flexdashboard::flex_dashboard(navbar = list(list(title = "Author", href = "https://jacob-long.com", icon = "fa-user-edit"), list(title = "Data Source", href = "https://covidtracking.com", icon = "fa-table"), list(title = paste("Updated:", format(Sys.Date(), "%B %e, %Y")), align = "left", icon = "far fa-clock")), source_code = "https://github.com/jacob-long/SC-COVID-19-Dashboard", css = "sc_dash.css", theme = "flatly", orientation = "row", vertical_layout = "fill"))'
      - name: Commit results
        run: |
          git commit sc_dashboard.html -m 'Re-build sc_dashboard.html'
          git push origin 