on:
  push:
    paths:
      - sc_dashboard.Rmd
  schedule: 
    - cron: '0 7 * * *' 

name: Render Dashboard

jobs:
  render:
    name: Render Dashboard
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Prepare repository
        run: git checkout "${GITHUB_REF:11}"
      - name: Install dependencies
        run: Rscript -e 'install.packages(c("rmarkdown", "flexdashboard", "tidyverse", "jtools", "lubridate", "extrafont", "ggplot2", "plotly"))'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("sc_dashboard.Rmd")'
      - name: Commit results
        run: |
          git commit sc_dashboard.html -m 'Re-build sc_dashboard.html'
          git push origin 